### PR TITLE
rehype-katex: update katex to 0.10.0

### PR DESCRIPTION
**Pull request by artragis**
Katex team released 0.10.0 package with many new features.

### CODE REVIEW

**Comment by artragis** [comment]
must I remove all package-lock or only rehype-katex one?

**Comment by wooorm** [comment]
@artragis Sorry scratch that, it’s fine the way it is. I wasn’t thinking!

**Comment by Rokt33r** [comment]
I've fixed it from here. It was needed lots of work because I have to fix the tests.
https://github.com/Rokt33r/remark-math/commit/fe06ec39e86802eaaab2d4d42b05ca7887b46362

**Comment by artragis** [comment]
Thanks, I was working on it, but thaks for your reactivity.

**Pull request closed without merging**
